# frozen_string_literal: true

source "https://gems.ruby-china.com"

# Specify your gem's dependencies in twitter.gemspec
gemspec

gem "canvas_text_helper", path: "../canvas_text_helper"
gem "html_text_helper", path: "../html_text_helper"

eval_gemfile("../gemfile_prefix.rb")
