# frozen_string_literal: true

source "https://gems.ruby-china.com"

gemspec

gem "json_token", path: "../json_token"
gem "paginated_collection", path: "../paginated_collection"

eval_gemfile("../gemfile_prefix.rb")
