# frozen_string_literal: true

source "https://gems.ruby-china.com"

gemspec

gem "canvas_cache", path: "../canvas_cache"
gem "canvas_slug", path: "../canvas_slug"
gem "config_file", path: "../config_file"
gem "legacy_multipart", path: "../legacy_multipart"

eval_gemfile("../gemfile_prefix.rb")
